# Generated by Django 5.0.2 on 2024-02-16 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctg_meal', to='meals.category'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='preperation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
